// this file was autogenerated by generate-dotenv.ts
// do not edit this file. instead edit .env.development.secret then rerun generate-dotenv.ts

import type { TProcessEnv } from "./dotenv.d.ts";

export const developmentsecretEnv: Partial<TProcessEnv> = {};
