// this file was autogenerated by generate-dotenv.ts
// do not edit this file. instead edit .env then rerun generate-dotenv.ts

export type TProcessEnv = {
    BASE_PATH: string;
    FIREBASE_STATIC_FILES_PATH: string;
    FIREBASE_API_KEY: string;
    FIREBASE_AUTH_DOMAIN: string;
    FIREBASE_DB_URL: string;
    FIREBASE_PROJECT_ID: string;
    FIREBASE_STORAGE_BUCKET: string;
    FIREBASE_MESSAGING_SENDER_ID: string;
    FIREBASE_APP_ID: string;
    FIREBASE_MEASUREMENT_ID: string;
    FIREBASE_LINK_ACCOUNTS: boolean;
    PROJECT_DOMAIN: string;
    PROJECT_NAME: string;
    NGROK_DEV_TUNNEL_NAME: string;
    VITE_PORT: number;
};
export const baseEnv: TProcessEnv = {
    BASE_PATH: "/",
    FIREBASE_STATIC_FILES_PATH: "/",
    FIREBASE_API_KEY: "AIzaSyB95EOVd6k5ItdhRVDKmPuAJ8zBwVXtKxc",
    FIREBASE_AUTH_DOMAIN: "something.firebaseapp.com",
    FIREBASE_DB_URL: "unused in this project",
    FIREBASE_PROJECT_ID: "auth-94762",
    FIREBASE_STORAGE_BUCKET: "unused in this project",
    FIREBASE_MESSAGING_SENDER_ID: "190381967079",
    FIREBASE_APP_ID: "1:190381967079:web:9436046b42e133ebf18442",
    FIREBASE_MEASUREMENT_ID: "G-QZB6RJE8ZS",
    FIREBASE_LINK_ACCOUNTS: false,
    PROJECT_DOMAIN: "something.ngrok-free.app",
    PROJECT_NAME: "Auth Test",
    NGROK_DEV_TUNNEL_NAME: "must match your ngrok tunnel name",
    VITE_PORT: 3000,
};
