// this file was autogenerated by generate-dotenv.ts
// do not edit this file. instead edit .env.development then rerun generate-dotenv.ts

import type { TProcessEnv } from "./dotenv.d.ts";

export const developmentEnv: Partial<TProcessEnv> = {
    PROJECT_DOMAIN: "something.ngrok-free.app",
    BASE_PATH: "/",
    FIREBASE_AUTH_DOMAIN: "auth.null.place",
    NGROK_DEV_TUNNEL_NAME: "must match your ngrok tunnel name",
    VITE_PORT: 3000,
    FIREBASE_STATIC_FILES_PATH: "/",
    FIREBASE_API_KEY: "AIzaSyB95EOVd6k5ItdhRVDKmPuAJ8zBwVXtKxc",
    FIREBASE_PROJECT_ID: "auth-94762",
    FIREBASE_MESSAGING_SENDER_ID: "190381967079",
    FIREBASE_APP_ID: "1:190381967079:web:9436046b42e133ebf18442",
    FIREBASE_MEASUREMENT_ID: "G-QZB6RJE8ZS",
    FIREBASE_LINK_ACCOUNTS: false,
};
