// file auto-generated by scripts/process-svg.ts
export type TEmailStateBoxKey = keyof typeof EmailSVGStateBoxCSSClass;
export type TEmailArrowKey = keyof typeof EmailSVGArrowCSSClass;
export type TEmailTransition = `${TEmailStateBoxKey}->${TEmailStateBoxKey}`;
export type TEmailSVGCSSClassKeys = TEmailArrowKey | TEmailStateBoxKey;

export const EmailSVGArrowCSSClass = {
    AutomaticallySubmitToFirebase0: "automatically-submit-to-firebase-0",
    ClearUserData0: "clear-user-data-0",
    Fail0: "fail-0",
    FirebaseReturnedAnError0: "firebase-returned-an-error-0",
    OkResponse0: "ok-response-0",
    OkResponse1: "ok-response-1",
    RequestEmailAddressFromUserAgain0:
        "request-email-address-from-user-again-0",
    Restart0: "restart-0",
    UserBeganTyping0: "user-began-typing-0",
    UserClickedLinkInEmail0: "user-clicked-link-in-email-0",
    UserClickedLinkInEmail1: "user-clicked-link-in-email-1",
    UserClickedLoginButton0: "user-clicked-login-button-0",
    UserDeletedAllInputText0: "user-deleted-all-input-text-0",
    UserIsTypingAgain0: "user-is-typing-again-0",
    UserSubmittedEmailAddressAgain0: "user-submitted-email-address-again-0",
} as const;

export const EmailSVGStateBoxCSSClass = {
    AuthFailed0: "auth-failed-0",
    AuthorisingViaFirebase0: "authorising-via-firebase-0",
    BadEmailAddress0: "bad-email-address-0",
    Idle0: "idle-0",
    SendingEmailAddressToFirebase0: "sending-email-address-to-firebase-0",
    SignedIn0: "signed-in-0",
    SignInLinkOpenedOnDifferentBrowser0:
        "sign-in-link-opened-on-different-browser-0",
    SignInLinkOpenedOnSameBrowser0: "sign-in-link-opened-on-same-browser-0",
    UserIsInputtingDetails0: "user-is-inputting-details-0",
    WaitingForEmailAddressInGui0: "waiting-for-email-address-in-gui-0",
    WaitingForUserToClickLinkInEmail0:
        "waiting-for-user-to-click-link-in-email-0",
} as const;
