// file auto-generated by scripts/process-svg.ts
export type TFacebookStateBoxKey = keyof typeof FacebookSVGStateBoxCSSClass;
export type TFacebookArrowKey = keyof typeof FacebookSVGArrowCSSClass;
export type TFacebookTransition =
    `${TFacebookStateBoxKey}->${TFacebookStateBoxKey}`;
export type TFacebookSVGCSSClassKeys = TFacebookArrowKey | TFacebookStateBoxKey;

export const FacebookSVGArrowCSSClass = {
    Fail0: "fail-0",
    FirebaseReturnedAnError0: "firebase-returned-an-error-0",
    OkResponse0: "ok-response-0",
    Reset0: "reset-0",
    Reset1: "reset-1",
    UserClickedLoginButton0: "user-clicked-login-button-0",
} as const;

export const FacebookSVGStateBoxCSSClass = {
    AuthFailed0: "auth-failed-0",
    FacebookIsUnavailable0: "facebook-is-unavailable-0",
    Idle0: "idle-0",
    RedirectingToFacebook0: "redirecting-to-facebook-0",
    SignedIn0: "signed-in-0",
} as const;
