// file auto-generated by scripts/process-svg.ts

export type TEmailSVGCSSClassKeys =
    | keyof typeof EmailSVGArrowCSSClass
    | keyof typeof EmailSVGStateBoxCSSClass;

export type TEmailSVGCSSClass =
    | typeof EmailSVGArrowCSSClass
    | typeof EmailSVGStateBoxCSSClass;

export const EmailSVGArrowCSSClass: Record<string, string> = {
    AutomaticallySubmitToFirebase0: "automatically-submit-to-firebase-0",
    DifferentEmailAddress0: "different-email-address-0",
    FirebaseReturnsAnError0: "firebase-returns-an-error-0",
    OkResponse0: "ok-response-0",
    OkResponse1: "ok-response-1",
    RequestEmailAddressFromUserAgain0:
        "request-email-address-from-user-again-0",
    SameEmailAddress0: "same-email-address-0",
    UserChangesEmailAddressAndClicksSignInWithEmailButton0:
        "user-changes-email-address-and-clicks-sign-in-with-email-button-0",
    UserClicksLinkInEmail0: "user-clicks-link-in-email-0",
    UserClicksLinkInEmail1: "user-clicks-link-in-email-1",
    UserInputsEmailAddressAndClicksSigninButton0:
        "user-inputs-email-address-and-clicks-signin-button-0",
} as const;

export const EmailSVGStateBoxCSSClass: Record<string, string> = {
    AuthorisingViaFirebase0: "authorising-via-firebase-0",
    BadEmailAddress0: "bad-email-address-0",
    EmailSubmittedToFirebase0: "email-submitted-to-firebase-0",
    Idle0: "idle-0",
    SignedIn0: "signed-in-0",
    SignInLinkOpenedOnDifferentBrowser0:
        "sign-in-link-opened-on-different-browser-0",
    SignInLinkOpenedOnSameBrowser0: "sign-in-link-opened-on-same-browser-0",
    WaitingForEmailAddressInGui0: "waiting-for-email-address-in-gui-0",
    WaitingForUserToClickLinkInEmail0:
        "waiting-for-user-to-click-link-in-email-0",
} as const;
