// file auto-generated by scripts/clean-svg.ts

export enum ArrowClass {

}

export enum StateBoxClass {
    UserInputsEmailAddressAndClicksSignInButton = "user-inputs-email-address-and-clicks-sign-in-button",
    UserClicksLinkInEmail = "user-clicks-link-in-email",
    UserClicksLinkInEmail1 = "user-clicks-link-in-email-1",
    AutomaticallySubmitToFirebase = "automatically-submit-to-firebase",
    RequestEmailAddressFromUserAgain = "request-email-address-from-user-again",
    FirebaseReturnsAnError = "firebase-returns-an-error",
    UserChangesEmailAddressAndClicksSignInWithEmailButton = "user-changes-email-address-and-clicks-sign-in-with-email-button",
    OkResponse = "ok-response",
    OkResponse1 = "ok-response-1",
    SameEmailAddress = "same-email-address",
    DifferentEmailAddress = "different-email-address",
}

