// file auto-generated by scripts/process-svg.ts
export type TEmailStateBoxKey = keyof typeof EmailSVGStateBoxCSSClass;
export type TEmailArrowKey = keyof typeof EmailSVGArrowCSSClass;
export type TEmailTransition = `${TEmailStateBoxKey}->${TEmailStateBoxKey}`;
export type TEmailSVGCSSClassKeys = TEmailArrowKey | TEmailStateBoxKey;

export const EmailSVGArrowCSSClass = {
    AutomaticallySubmitToFirebase0: "automatically-submit-to-firebase-0",
    DifferentEmailAddress0: "different-email-address-0",
    FirebaseReturnsAnError0: "firebase-returns-an-error-0",
    OkResponse0: "ok-response-0",
    OkResponse1: "ok-response-1",
    RequestEmailAddressFromUserAgain0:
        "request-email-address-from-user-again-0",
    SameEmailAddress0: "same-email-address-0",
    UserBeganTyping0: "user-began-typing-0",
    UserChangesEmailAddressAndClicksSignInWithEmailButton0:
        "user-changes-email-address-and-clicks-sign-in-with-email-button-0",
    UserClickedSubmitButton0: "user-clicked-submit-button-0",
    UserClicksLinkInEmail0: "user-clicks-link-in-email-0",
    UserClicksLinkInEmail1: "user-clicks-link-in-email-1",
    UserDeletedAllInputText0: "user-deleted-all-input-text-0",
} as const;

export const EmailSVGStateBoxCSSClass = {
    AuthorisingViaFirebase0: "authorising-via-firebase-0",
    BadEmailAddress0: "bad-email-address-0",
    Idle0: "idle-0",
    SendingEmailToFirebase0: "sending-email-to-firebase-0",
    SignedIn0: "signed-in-0",
    SignInLinkOpenedOnDifferentBrowser0:
        "sign-in-link-opened-on-different-browser-0",
    SignInLinkOpenedOnSameBrowser0: "sign-in-link-opened-on-same-browser-0",
    UserIsInputtingDetails0: "user-is-inputting-details-0",
    WaitingForEmailAddressInGui0: "waiting-for-email-address-in-gui-0",
    WaitingForUserToClickLinkInEmail0:
        "waiting-for-user-to-click-link-in-email-0",
} as const;
