// file auto-generated by scripts/process-svg.ts
export type TGoogleStateBoxKey = keyof typeof GoogleSVGStateBoxCSSClass;
export type TGoogleArrowKey = keyof typeof GoogleSVGArrowCSSClass;
export type TGoogleTransition = `${TGoogleStateBoxKey}->${TGoogleStateBoxKey}`;
export type TGoogleSVGCSSClassKeys = TGoogleArrowKey | TGoogleStateBoxKey;

export const GoogleSVGArrowCSSClass = {
    Fail0: "fail-0",
    FirebaseReturnedAnError0: "firebase-returned-an-error-0",
    OkResponse0: "ok-response-0",
    OkResponse1: "ok-response-1",
    Reset0: "reset-0",
    Reset1: "reset-1",
    UserClickedLoginButton0: "user-clicked-login-button-0",
} as const;

export const GoogleSVGStateBoxCSSClass = {
    AuthFailed0: "auth-failed-0",
    GoogleIsUnavailable0: "google-is-unavailable-0",
    GoogleResponded0: "google-responded-0",
    Idle0: "idle-0",
    RedirectingToGoogle0: "redirecting-to-google-0",
    SignedIn0: "signed-in-0",
} as const;
