// file auto-generated by scripts/process-svg.ts
export type TGithubStateBoxKey = keyof typeof GithubSVGStateBoxCSSClass;
export type TGithubArrowKey = keyof typeof GithubSVGArrowCSSClass;
export type TGithubTransition = `${TGithubStateBoxKey}->${TGithubStateBoxKey}`;
export type TGithubSVGCSSClassKeys = TGithubArrowKey | TGithubStateBoxKey;

export const GithubSVGArrowCSSClass = {
    Fail0: "fail-0",
    FirebaseReturnedAnError0: "firebase-returned-an-error-0",
    OkResponse0: "ok-response-0",
    OkResponse1: "ok-response-1",
    Reset0: "reset-0",
    Reset1: "reset-1",
    UserClickedLoginButton0: "user-clicked-login-button-0",
} as const;

export const GithubSVGStateBoxCSSClass = {
    AuthFailed0: "auth-failed-0",
    GithubIsUnavailable0: "github-is-unavailable-0",
    GithubResponded0: "github-responded-0",
    Idle0: "idle-0",
    RedirectingToGithub0: "redirecting-to-github-0",
    SignedIn0: "signed-in-0",
} as const;
