// file auto-generated by scripts/process-svg.ts
export type TEmailStateBoxKey = keyof typeof EmailSVGStateBoxCSSClass;
export type TEmailArrowKey = keyof typeof EmailSVGArrowCSSClass;
export type TEmailTransition = `${TEmailStateBoxKey}->${TEmailStateBoxKey}`;
export type TEmailSVGCSSClassKeys = TEmailArrowKey | TEmailStateBoxKey;

export const EmailSVGArrowCSSClass = {
    Fail0: "fail-0",
    FirebaseReturnedAnError0: "firebase-returned-an-error-0",
    OkResponse0: "ok-response-0",
    OkResponse1: "ok-response-1",
    Reset0: "reset-0",
    Reset1: "reset-1",
    UserClickedLoginButton0: "user-clicked-login-button-0",
} as const;

export const EmailSVGStateBoxCSSClass = {
    AuthFailed0: "auth-failed-0",
    GithubIsUnavailable0: "github-is-unavailable-0",
    GithubResponded0: "github-responded-0",
    Idle0: "idle-0",
    RedirectingToGithub0: "redirecting-to-github-0",
    SignedIn0: "signed-in-0",
} as const;
