// file auto-generated by scripts/process-svg.ts
export type TFacebookStateBoxKey = keyof typeof FacebookSVGStateBoxCSSClass;
export type TFacebookArrowKey = keyof typeof FacebookSVGArrowCSSClass;
export type TFacebookTransition =
    `${TFacebookStateBoxKey}->${TFacebookStateBoxKey}`;
export type TFacebookSVGCSSClassKeys = TFacebookArrowKey | TFacebookStateBoxKey;

export const FacebookSVGArrowCSSClass = {
    AndWereBack0: "and-were-back-0",
    DownloadProfilePic0: "download-profile-pic-0",
    Fail0: "fail-0",
    FirebaseReturnedAnError0: "firebase-returned-an-error-0",
    GraphApiFail0: "graph-api-fail-0",
    LogoutButtonClicked0: "logout-button-clicked-0",
    LogoutButtonClicked1: "logout-button-clicked-1",
    LogoutButtonClicked2: "logout-button-clicked-2",
    LogoutButtonClicked3: "logout-button-clicked-3",
    LogoutSuccessful0: "logout-successful-0",
    OkResponse0: "ok-response-0",
    Reset0: "reset-0",
    Reset1: "reset-1",
    Reset2: "reset-2",
    UserClickedLoginButton0: "user-clicked-login-button-0",
} as const;

export const FacebookSVGStateBoxCSSClass = {
    AuthFailed0: "auth-failed-0",
    CheckingRedirectResult0: "checking-redirect-result-0",
    FacebookIsUnavailable0: "facebook-is-unavailable-0",
    FailedToGetProfilePic0: "failed-to-get-profile-pic-0",
    GotProfilePic0: "got-profile-pic-0",
    Idle0: "idle-0",
    RedirectingToFacebook0: "redirecting-to-facebook-0",
    SentLogoutRequest0: "sent-logout-request-0",
    SignedIn0: "signed-in-0",
} as const;
